### ISSUE TITLE
Cannot connect to ROS master at http://10.0.2.15:11311

### ISSUE THREAD

**Issue by zhaozj89** [mathworks-robotics/templates-robocup-robot-manipulation-challenge#1]
Hi, after following the instructions, I came across the problem that cannot to ROS master at http://10.0.2.15:1131.

I saw the default network setting is NAT, and have tried this https://www.mathworks.com/matlabcentral/answers/392422-cannot-connect-to-ros-master-running-on-virtual-machine to change NAT to bridge adapter. But in that case, I cannot open the ROS application in VM because it cannot connect to the network. 

I would like to ask what could be the problem. Thanks very much.

My environment is:

macOS Monterey
Matlab 2021b

**Comment by javendanoarb** [comment]
@zhaozj89 Thanks for pointing that out. We will add info for changing the bridging options for MAC and Linux.

**Comment by zhaozj89** [comment]
Thanks. It works now.
